Repository Google-Developer-Student-Club-Dearborn/hd2-website, pull requests merged in 2023-04, with the labels that each got.

#7 [chore] Add name to `authors.txt` as per #1
  authors.txt
Labels: good first issue

#6 Add author name
  authors.txt
Labels: documentation

#2 Setup project structure
  .gitignore
  Dockerfile
  README.md
  bun.lockb
  bunfig.toml
  docker-compose.yml
  index.ts
  next.config.cjs
  package-lock.json
  package.json
  pages/.next/cache/config.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  postcss.config.cjs
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  rome.json
  styles/globals.css
  tailwind.config.cjs
  tsconfig.json
  turbo.json
Labels: enhancement
